airline/airline/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    BookingDetailView,
    BookingsView,
    NewBookingPaymentView,
    NewBookingView,
    RegisterView,
    TravellerView,
    TripsView,
)

urlpatterns = [
    # fmt: off
    path("login/", LoginView.as_view(template_name="airline/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("traveller/", TravellerView.as_view(), name="traveller"),
    path("book/", NewBookingView.as_view(), name="new-booking"),
    path("booking/<pk>/payment/", NewBookingPaymentView.as_view(), name="new-booking-payment"),
    path("booking/<pk>/", BookingDetailView.as_view(), name="booking"),
    path("bookings/", BookingsView.as_view(), name="bookings"),
    path("trips/", TripsView.as_view(), name="trips"),
    path("", TemplateView.as_view(template_name="airline/index.html"), name="index"),
    # fmt: on
]

airline/airline/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils.crypto import get_random_string
from django.utils import timezone


class Flight(models.Model):
    departure_airport = models.CharField(max_length=50)
    departure_time = models.TimeField()
    departure_tz = models.CharField(max_length=50)
    arrival_airport = models.CharField(max_length=50)
    arrival_tz = models.CharField(max_length=50)
    duration = models.DurationField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.departure_airport} - {self.arrival_airport} ({self.price})"


class TravellerManager(BaseUserManager):
    def create(self, username, password, name, dob):
        """
        Create and save a user with the given username, password, name and dob.
        """
        traveller = self.model(username=username, name=name, dob=dob)
        traveller.set_password(password)
        traveller.save(using=self._db)
        return traveller


class Traveller(AbstractBaseUser):
    username = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=250)
    dob = models.DateField()

    objects = TravellerManager()

    USERNAME_FIELD = "username"

    def __str__(self):
        return self.name


def get_booking_id():
    def get_id():
        return get_random_string(
            length=6, allowed_chars="ABCDEFGHKLMNPRSTUVWXYZ23456789"
        )

    id = get_id()
    while Booking.objects.filter(id=id).exists():
        id = get_id()
    return id


class Booking(models.Model):
    PAYMENT_PENDING = "pending"
    PAYMENT_DONE = "done"
    PAYMENT_CHOICES = (
        (PAYMENT_PENDING, PAYMENT_PENDING.title()),
        (PAYMENT_DONE, PAYMENT_DONE.title()),
    )
    id = models.CharField(max_length=6, default=get_booking_id, primary_key=True)
    buyer = models.ForeignKey(
        Traveller, on_delete=models.PROTECT, related_name="purchased_bookings"
    )
    booking_date = models.DateTimeField(default=timezone.now)
    travellers = models.ManyToManyField(Traveller, related_name="bookings")
    flight = models.ForeignKey(
        Flight, on_delete=models.PROTECT, related_name="bookings"
    )
    departure_date = models.DateTimeField()
    arrival_date = models.DateTimeField()
    payment_status = models.CharField(
        max_length=7, choices=PAYMENT_CHOICES, default=PAYMENT_PENDING
    )

    class Meta:
        ordering = ("booking_date",)

    def __str__(self):
        return self.id

airline/airline/forms.py
import datetime

import arrow
import requests
import structlog
from django import forms
from django.conf import settings

from .models import Traveller, Booking

logger = structlog.get_logger("structlog")


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Traveller
        fields = ("username", "password", "name", "dob")
        widgets = {"password": forms.PasswordInput}

    def save(self, *args, **kwargs):
        cd = self.cleaned_data
        traveller = Traveller.objects.create(
            cd["username"], cd["password"], cd["name"], cd["dob"]
        )
        logger.bind(user_id=traveller.id)
        logger.info("new_traveller", user_id=traveller.id)
        return traveller


class NewBookingForm(forms.ModelForm):

    departure_date = forms.DateField()

    class Meta:
        model = Booking
        fields = ("travellers", "flight")

    def save(self, commit=True):
        flight = self.instance.flight
        departure = arrow.get(
            datetime.datetime.combine(
                self.cleaned_data["departure_date"], flight.departure_time
            ),
            flight.departure_tz,
        )
        arrival = (departure + flight.duration).to(flight.arrival_tz)
        self.instance.departure_date = departure.datetime
        self.instance.arrival_date = arrival.datetime
        return super().save(commit=commit)


PAYMENT_OPTION_WIRE = "wire"
PAYMENT_OPTION_CHECK = "check"
PAYMENT_OPTION_CHOICES = (
    (PAYMENT_OPTION_WIRE, "Wire transfer"),
    (PAYMENT_OPTION_CHECK, "Check deposit"),
)


class NewBookingPaymentForm(forms.Form):
    payment_option = forms.ChoiceField(choices=PAYMENT_OPTION_CHOICES, required=True)

    wire_bank = forms.ChoiceField(
        required=False, choices=(("westbank", "westbank"), ("eastbank", "eastbank"))
    )
    wire_username = forms.CharField(required=False)
    wire_password = forms.CharField(required=False, widget=forms.PasswordInput)

    check_number = forms.CharField(required=False)

    def clean(self):
        cd = self.cleaned_data
        if cd["payment_option"] == PAYMENT_OPTION_CHECK:
            if "check_number" not in cd:
                self.add_error(
                    "check_number", self.check_number.error_messages["required"]
                )
        elif cd["payment_option"] == PAYMENT_OPTION_WIRE:
            if "wire_bank" not in cd:
                self.add_error("wire_bank", self.wire_bank.error_messages["required"])
            if "wire_username" not in cd:
                self.add_error(
                    "wire_username", self.wire_username.error_messages["required"]
                )
            if "wire_password" not in cd:
                self.add_error(
                    "wire_password", self.wire_password.error_messages["required"]
                )
        return self.cleaned_data

airline/airline/views.py
import structlog

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models, transaction
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DetailView, FormView, ListView
from requests.exceptions import HTTPError

from .forms import NewBookingForm, NewBookingPaymentForm, RegisterForm
from .models import Booking, Traveller
from .payment import PaymentClient

logger = structlog.get_logger("structlog")


class TravellerView(LoginRequiredMixin, DetailView):
    template_name = "airline/traveller.html"

    def get_context_data(self, **kwargs):
        next_trip_booking = (
            Booking.objects.filter(
                departure_date__gte=timezone.now(), travellers__id=self.request.user.pk
            )
            .select_related("flight")
            .first()
        )
        return super().get_context_data(next_trip=next_trip_booking)

    def get_object(self):
        return self.request.user


class RegisterView(CreateView):
    model = Traveller
    form_class = RegisterForm
    template_name = "airline/register.html"
    success_url = reverse_lazy("traveller")


class BookingDetailView(LoginRequiredMixin, DetailView):
    model = Booking
    template_name = "airline/booking.html"

    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        # fmt: off
        q = (
            models.Q(buyer=user)
            | models.Q(travellers=user, payment_status=Booking.PAYMENT_DONE)
        )
        # fmt: on
        return (
            qs.filter(q)
            .select_related("flight", "buyer")
            .prefetch_related("travellers")
            .order_by("departure_date")
        )


class BookingsView(LoginRequiredMixin, ListView):
    model = Booking
    template_name = "airline/bookings.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = (
            qs.filter(buyer=self.request.user)
            .annotate(
                order=models.Case(
                    models.When(
                        then=models.Value(0), payment_status=Booking.PAYMENT_DONE
                    ),
                    models.When(
                        then=models.Value(1), payment_status=Booking.PAYMENT_PENDING
                    ),
                    output_field=models.SmallIntegerField(),
                )
            )
            .select_related("flight")
            .order_by("order", "departure_date")
        )
        return qs


class TripsView(LoginRequiredMixin, ListView):
    model = Booking
    template_name = "airline/trips.html"

    def get_queryset(self):
        user = self.request.user
        # fmt: off
        q = (
            models.Q(buyer=user)
            | models.Q(travellers=user, payment_status=Booking.PAYMENT_DONE)
        )
        # fmt: on
        return Booking.objects.filter(q).select_related("flight")


class NewBookingView(LoginRequiredMixin, CreateView):
    model = Booking
    form_class = NewBookingForm
    template_name = "airline/new_booking.html"

    def get_success_url(self):
        return reverse("new-booking-payment", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        obj = form.instance
        obj.buyer = self.request.user
        return super().form_valid(form)


class NewBookingPaymentView(LoginRequiredMixin, FormView):
    form_class = NewBookingPaymentForm
    template_name = "airline/new_booking_payment.html"
    success_url = reverse_lazy("traveller")

    def get_object(self, *, for_update=False):
        qs = Booking.objects.filter(
            payment_status=Booking.PAYMENT_PENDING
        ).select_related("flight")
        if for_update:
            qs = qs.select_for_update()
        return qs.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        return super().get_context_data(booking=self.get_object())

    def form_valid(self, form):
        with structlog.threadlocal.tmp_bind(logger, booking_id=self.kwargs["pk"]):
            try:
                logger.info("payment_starting")
                with transaction.atomic():
                    obj = self.get_object(for_update=True)
                    obj.payment_status = Booking.PAYMENT_DONE
                    obj.save(update_fields=["payment_status"])
                    payment_client = PaymentClient(obj, self.request.trace_id)
                    payment_client.process(**form.cleaned_data)
            except HTTPError:
                form.add_error(None, "Error processing payment!")
                return super().form_invalid(form)

            logger.info("payment_finished")
            return super().form_valid(form)

airline/airline/templates/airline/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'airline/css/bootstrap.min.css' %}"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Logging Rethought 2: The Actions of Frank Taylor Jr.</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'index' %}">FlyMe</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'new-booking' %}">Book Flight</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'bookings' %}">My Bookings</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'trips' %}">My Trips</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container mt-5">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-light">
        <nav class="navbar fixed navbar-light bg-light">
            <span class="navbar-text">
                Copyright &copy; 2019 by <a href="https://markusholtermann.eu/">Markus Holtermann</a>
            </span>
        </nav>
        <div class="container small">
            <div class="row">
                <div class="col-sm-12 col-md-4 col-lg-2 offset-lg-3 mt-3">
                    <div class="row">
                        <div class="col">
                            <strong>Travel</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'new-booking' %}">Book Flights</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'bookings' %}">My Bookings</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'trips' %}">My Trips</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4 col-lg-2 mt-3">
                    <div class="row">
                        <div class="col">
                            <strong>Company</strong>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4 col-lg-2 mt-3">
                    <div class="row">
                        <div class="col">
                            <strong>Legal</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <small>*</small>Conditions apply
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'airline/js/jquery-3.3.1.slim.min.js' %}"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="{% static 'airline/js/bootstrap.bundle.min.js' %}"
        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
        crossorigin="anonymous"></script>
</body>

</html>

airline/airline/templates/airline/booking.html
{% extends "airline/base.html" %}
{% load tz %}

{% block content %}
<table class="table table-striped">
    <tbody>
        <tr>
            <th scope="col">Booking ID</th>
            <td scope="row">{{ object.id }}</td>
        </tr>
        <tr>
            <th scope="col">Booking date</th>
            <td scope="row">{{ object.booking_date }}</td>
        </tr>
        <tr>
            <th scope="col">Buyer</th>
            <td scope="row">{{ object.buyer }}</td>
        </tr>
        <tr>
            <th scope="col">Departure airport</th>
            <td>{{ object.flight.departure_airport }}</td>
        </tr>
        <tr>
            <th scope="col">Arrival airport</th>
            <td>{{ object.flight.arrival_airport }}</td>
        </tr>
        <tr>
            <th scope="col">Departure time</th>
            <td>{{ object.departure_date | timezone:object.flight.departure_tz | date:"Y-M-d H:i" }}</td>
        </tr>
        <tr>
            <th scope="col">Arrival time</th>
            <td>{{ object.arrival_date | timezone:object.flight.arrival_tz | date:"Y-M-d H:i" }}</td>
        </tr>
        <tr>
            <th scope="col">Duration</th>
            <td>{{ object.flight.duration }}</td>
        </tr>
        <tr>
            <th scope="col">Travellers</th>
            <td>{% for traveller in object.travellers.all %}{% if not forloop.first %}, {% endif %}{{ traveller }}{% endfor %}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

airline/airline/templates/airline/bookings.html
{% extends "airline/base.html" %}
{% load tz %}

{% block content %}
<h1>Your bookings!</h1>

{% if object_list %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Booking ID</th>
            <th scope="col">Departure airport</th>
            <th scope="col">Departure time</th>
            <th scope="col">Arrival time</th>
            <th scope="col">Arrival airport</th>
            <th scope="col">Payment</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in object_list %}
        <tr>
            <td scope="row"><a href="{% url 'booking' pk=booking.pk %}">{{ booking.pk }}</a></td>
            <td>{{ booking.flight.departure_airport }}</td>
            <td>{{ booking.departure_date | timezone:booking.flight.departure_tz | date:"Y-M-d H:i" }}</td>
            <td>{{ booking.arrival_date | timezone:booking.flight.arrival_tz | date:"Y-M-d H:i" }}</td>
            <td>{{ booking.flight.arrival_airport }}</td>
            <td>{% if booking.payment_status == "pending" %}<a href="{% url 'new-booking-payment' pk=booking.pk %}">{{ booking.get_payment_status_display }}</a>{% else %}{{ booking.get_payment_status_display }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
No bookings yet!
{% endif %}
{% endblock %}

airline/airline/templates/airline/index.html
{% extends "airline/base.html" %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <div class="display-3">We FlyYou wherever <strong>you</strong><small style="font-size: 1rem;vertical-align: super;" class="small">*</small> want!</div>
    </div>
</div>
{% endblock %}

airline/airline/templates/airline/login.html
{% extends "airline/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="mx-auto" style="width: 30rem;">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

airline/airline/templates/airline/new_booking.html
{% extends "airline/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="mx-auto" style="width: 30rem;">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

airline/airline/templates/airline/new_booking_payment.html
{% extends "airline/base.html" %}
{% load tz %}
{% load bootstrap4 %}

{% block content %}
{{ booking.flight }} on {{ booking.departure_date | timezone:booking.flight.departure_tz | date:"Y-M-d H:i" }}
<div class="mx-auto" style="width: 30rem;">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Pay</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

airline/airline/templates/airline/register.html
{% extends "airline/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="mx-auto" style="width: 30rem;">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

airline/airline/templates/airline/traveller.html
{% extends "airline/base.html" %}

{% block content %}
<h1>Hello {{ object.name }}!</h1>

{% if next_trip %}
<p>Your next trip to {{ next_trip.flight.arrival_airport }} at {{ next_trip.departure_date }}.</p>
{% else %}
<p>You don't have any upcoming trip!</p>
{% endif %}
{% endblock %}

airline/airline/templates/airline/trips.html
{% extends "airline/base.html" %}
{% load tz %}

{% block content %}
<h1>Your bookings!</h1>

{% if object_list %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Booking ID</th>
            <th scope="col">Departure airport</th>
            <th scope="col">Departure time</th>
            <th scope="col">Arrival time</th>
            <th scope="col">Arrival airport</th>
            <th scope="col">Duration</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in object_list %}
        <tr>
            <td scope="row"><a href="{% url 'booking' pk=booking.pk %}">{{ booking.pk }}</a></td>
            <td>{{ booking.flight.departure_airport }}</td>
            <td>{{ booking.departure_date | timezone:booking.flight.departure_tz | date:"Y-M-d H:i" }}</td>
            <td>{{ booking.arrival_date | timezone:booking.flight.arrival_tz | date:"Y-M-d H:i" }}</td>
            <td>{{ booking.flight.arrival_airport }}</td>
            <td>{{ booking.flight.duration }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
No bookings yet!
{% endif %}
{% endblock %}